version: '2'

services:
  #API
  ma-api:
    container_name: ma-api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      ma:
        aliases:
          - ma-api.com
    environment:
      VIRTUAL_HOST: ma-api.com
  #FRONT
  # ma-front:
  #   container_name: ma-front
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   environment:
  #     VIRTUAL_HOST: www.MAmessagerie.com
  #   volumes:
  #     - ./front:/root/MA
  #     - ma_front_node_modules:/root/ma/node_modules
  #SERVER
  maproxy:
    container_name: maproxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - mavhost:/etc/nginx/vhost.d
      - mahtml:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      ma:

volumes:
  mahtml:
  mavhost:
  ma_front_node_modules:

networks:
  ma:
    driver: bridge
